#!/bin/bash
# post-install finalize script
# Shows completion message and next steps

echo ""
echo "============================================"
echo "       Dotfiles Installation Complete!     "
echo "============================================"
echo ""
echo "Next steps:"
echo ""
echo "  1. Reboot your system:"
echo "     sudo reboot"
echo ""
echo "  2. After reboot, login with Hyprland"
echo ""
echo "  3. Your configurations:"
echo "     - Hyprland: ~/.config/hypr/"
echo "       (core/ = defaults, local/ = your overrides)"
echo "     - QuickShell: ~/.config/quickshell/"
echo "     - Ghostty: ~/.config/ghostty/"
echo "     - Scripts: ~/.local/bin/scripts/"
echo ""
echo "  4. To update dotfiles later:"
echo "     dotfiles-update"
echo ""
echo "  5. To check version:"
echo "     dotfiles-version"
echo ""
echo "============================================"
echo ""
