hl.on("hyprland.start", function()
  hl.exec_cmd("awww-daemon &")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("qs &")
  hl.exec_cmd("hypridle &")
  hl.exec_cmd("~/.local/bin/scripts/set-permissions.sh")
  hl.exec_cmd("kwalletd5")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user start xdg-desktop-portal")
  hl.exec_cmd("xhost +local:docker")
  hl.exec_cmd("sleep 3 && hyprctl keyword misc:initial_workspace_tracking true")
end)
