bind = , XF86Launch4, exec, ~/.local/bin/scripts/platform-profile.sh
bind = , XF86KbdBrightnessUp, exec, ~/.local/bin/scripts/keyboard-backlight.sh up
bind = , XF86KbdBrightnessDown, exec, ~/.local/bin/scripts/keyboard-backlight.sh down
bind = , XF86Launch3, exec, asusctl aura effect --next-mode
bind = $mainMod+Ctrl, K, exec, ~/.local/bin/scripts/keyboard-theme-sync.sh
bind = $mainMod+Ctrl+Shift, K, exec, ~/.local/bin/scripts/keyboard-led-off.sh
bind = $mainMod+Ctrl, G, exec, ~/.local/bin/scripts/gpu-toggle.sh
bind = $mainMod+Ctrl, B, exec, ~/.local/bin/scripts/battery-status.sh
bindl = , XF86TouchpadToggle, exec, ~/.local/bin/scripts/touchpad-toggle.sh
