# ~/.config/hypr/hypridle.conf

general {
    lock_cmd = pidof hyprlock || hyprlock       # Command to lock the screen
    unlock_cmd = pkill -x hyprlock              # Command to unlock
    before_sleep_cmd = pidof hyprlock || hyprlock    # Command to run before sleep
    after_sleep_cmd = hyprctl dispatch dpms on  # Command to run after sleep
    ignore_dbus_inhibit = false                 # Enable D-Bus inhibit detection
}

# This listener turns the screen off after 5 minutes of inactivity, but only if no audio is playing
listener {
    timeout = 14400                                # 1800 seconds = 30 minutes
    on-timeout = bash -c 'if ! pgrep -f "(firefox|chromium|mpv|vlc|spotify)" > /dev/null && ! pacmd list-sink-inputs | grep -q "state: RUNNING"; then hyprctl dispatch dpms off; fi'
    on-resume = hyprctl dispatch dpms on         # Command to turn screen back on when resumed
}

# This listener locks the screen after 10 minutes of inactivity
listener {
    timeout = 14400                                # 600 seconds = 10 minutes
    on-timeout = pidof hyprlock || hyprlock           # Lock with hyprlock instead of ending session
}

# This listener suspends the system after 30 minutes of inactivity
listener {
    timeout = 14400 # 1800 seconds = 30 minutes
    on-timeout = systemctl suspend               # Command to suspend the system
}
