-- Hyprland Lua Configuration
-- Layered config system: core/ + hardware files + colors

-- Core defaults (from dotfiles repo, may be updated)
require("core/programs")
require("core/environment")
require("core/appearance")
require("core/input")
require("core/layout")
require("core/keybinds")
require("core/windowrules")
require("core/monitors")
require("core/autostart")

-- Hardware-specific (placeholders, populated during install)
require("nvidia")
require("asus")

-- Dynamic theme colors (generated by matugen on wallpaper change)
pcall(require, "colors")
